<a href="https://colab.research.google.com/github/Danzigerrr/PyTorch-Practice/blob/Practice-1/Tensor_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# TENSORS

- A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
- Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
- Default data type of float32.
- More suitable for deep learning than a numpy array.



## Normal list

In [ ]:
my_list = [[1,2,3], [4,5,6], [7,8,9]]
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## Numpy list

In [ ]:
import numpy as np

In [ ]:
np1 = np.array(my_list)
np1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np2 = np.random.rand(5)
np2

array([0.67343049, 0.40182019, 0.45552821, 0.36952321, 0.95915559])

## PyTorch tensor

In [ ]:
import torch

In [ ]:
tensor_2d = torch.randn(3,6)
tensor_2d

tensor([[-1.1771,  0.0112, -1.0511, -1.7508,  1.2452, -0.4709],
        [ 0.7712,  0.9913,  0.4138,  1.1111,  0.3449, -1.0989],
        [ 0.6314,  0.8992,  0.2228, -0.5353, -0.4907, -0.1657]])

In [ ]:
tensor_3d = torch.randn(3,6,7)
tensor_3d

tensor([[[-0.4045, -1.3636,  0.6546,  1.3528, -0.1329, -0.1440,  0.1978],
         [-1.9448,  0.5967, -0.5061,  1.1489, -1.3112,  0.5778,  0.8290],
         [ 0.0114,  0.4072, -1.0174,  1.0044,  0.4973, -0.1366, -1.2101],
         [-0.7985, -1.5179,  0.2846,  1.5445, -0.5492,  0.5987,  0.8227],
         [ 0.3033, -0.4354, -0.2588, -0.3435,  0.6427, -1.4902, -1.0297],
         [-2.5860,  0.9009,  0.4070,  1.8775,  0.8810, -0.8802, -0.8829]],

        [[-1.1868, -0.6343,  1.2003, -1.0584, -0.4823,  1.2490,  0.5289],
         [-0.4010, -0.9174, -1.1150, -1.3565,  0.5636, -0.3414,  0.5438],
         [ 0.4472, -0.5389,  2.0707,  0.3373, -0.5339, -0.4005,  0.6938],
         [-1.0592, -1.2221, -0.0918, -1.4597,  0.3190, -1.3267, -0.5818],
         [-0.2031,  0.2930,  1.0165, -0.1576,  1.4738, -0.2738,  0.6337],
         [ 0.3758, -0.3863, -0.9164,  0.5072,  0.8621, -0.9447, -1.0513]],

        [[ 1.4789,  2.0841, -1.6133,  1.3053,  0.4652,  0.8213,  1.6008],
         [-1.2285,  1.5805,  0.349

### Tensor from numpy array

In [ ]:
tensor_from_numpy = torch.from_numpy(np1)
tensor_from_numpy

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])