<a href="https://colab.research.google.com/github/Danzigerrr/PyTorch-Practice/blob/Practice-1/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Torch Operations

In [1]:
import torch

In [6]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reshape and view

In [7]:
my_torch_reshaped = my_torch.reshape(2,5)
my_torch_reshaped

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Reshape method if we don't know the size of the tensor


In [12]:
my_torch2 = torch.arange(20)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [13]:
my_torch2_reshaped_1 = my_torch2.reshape(2,-1)
my_torch2_reshaped_1

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [14]:
my_torch2_reshaped_2 = my_torch2.reshape(-1,2)
my_torch2_reshaped_2

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])

In [15]:
my_torch2_viewed = my_torch2.view(2,10)
my_torch2_viewed

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

### view and reshape use values from the original tensors


In [18]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch4 = my_torch3.reshape(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
# change in the original tensor (the first one)
my_torch3[5] = 999

In [22]:
my_torch3

tensor([  0,   1,   2,   3,   4, 999,   6,   7,   8,   9])

In [23]:
my_torch4

tensor([[  0,   1,   2,   3,   4],
        [999,   6,   7,   8,   9]])

## Slices
Allow you to take a part of a tensor

In [25]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# one item --> keep in mind it is a tensor, not a number (int)
my_torch5[9]

tensor(9)

In [33]:
my_torch6 = my_torch5.reshape(5,2)
my_torch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [35]:
my_torch6[:,1]

tensor([1, 3, 5, 7, 9])

In [37]:
my_torch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])