<a href="https://colab.research.google.com/github/Danzigerrr/PyTorch-Practice/blob/Practice-1/Tensor_math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Math Operations

## Basic operations

In [1]:
import torch
import numpy as np

In [21]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

### Addition

In [3]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

### Substraction

In [5]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [6]:
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

### Multiply

In [7]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

### Division

In [9]:
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [10]:
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

### Modulus

In [11]:
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [13]:
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

### Exponents

In [14]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [15]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

## Reassignment

In [24]:
tensor_a_reassign_1 = tensor_a + tensor_b
tensor_a_reassign_1

tensor([11, 14, 17, 20])

to write it shorter use *add_()* instead of *add()*

In [25]:
tensor_a.add_(tensor_b)
tensor_a

tensor([11, 14, 17, 20])